server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/2fa/**, /api/sessions/**, /api/settings/**
          filters:
            - JwtAuthFilter
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/user

        - id: vault-service
          uri: lb://vault-service
          predicates:
            - Path=/api/vault/**, /api/categories/**, /api/folders/**, /api/shares/**, /api/backup/**
          filters:
            - JwtAuthFilter
            - name: CircuitBreaker
              args:
                name: vaultServiceCB

        - id: generator-service
          uri: lb://generator-service
          predicates:
            - Path=/api/generator/**

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/security/**, /api/dashboard/**
          filters:
            - JwtAuthFilter


        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - JwtAuthFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}
