spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/2fa/**, /api/sessions/**, /api/settings/**
          filters:
            - JwtAuthFilter
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/user

        - id: vault-service
          uri: lb://vault-service
          predicates:
            - Path=/api/vault/**, /api/categories/**, /api/folders/**, /api/shares/**, /api/backup/**
          filters:
            - JwtAuthFilter
            - name: CircuitBreaker
              args:
                name: vaultServiceCB

        - id: generator-service
          uri: lb://generator-service
          predicates:
            - Path=/api/generator/**

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/security/**, /api/dashboard/**
          filters:
            - JwtAuthFilter


        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - JwtAuthFilter
